---
- name: List configured runners as json
  ansible.builtin.command: "{{ gitlab_runner_executable }} --log-format json list"
  register: registered_runners_json_result
  changed_when: false
  check_mode: false
  become: "{{ gitlab_runner_system_mode }}"

- name: Filter valid JSON lines
  ansible.builtin.set_fact:
    valid_json_lines: "{{ registered_runners_json_result.stderr_lines | select('search', '^\\{.*\\}$') | list }}"

- name: Initialze runner list
  ansible.builtin.set_fact:
    registered_gitlab_runner_names: []

- name: Create list of configured runners
  ansible.builtin.set_fact:
    registered_gitlab_runner_names: "{{ registered_gitlab_runner_names + [json_item['msg']] }}"
  vars:
    json_item: "{{ item | from_json }}"
  loop: "{{ valid_json_lines }}"
  when: json_item.get('Executor') is defined
  no_log: "{{ gitlab_runner_no_log_secrets | default(omit) }}"

- name: Print registered runners
  ansible.builtin.debug:
    var: registered_gitlab_runner_names
