---

- name: Creating a new directory for docker compose file
  file:
    path: /root/gitlab-runner
    state: directory
    mode: '0755'

- name: Copy compose config file
  copy:
    src: "{{ role_path }}/templates/.env"
    dest: /root/gitlab-runner/

- name: Copy Docker Compose file
  copy:
    src: "{{ role_path }}/templates/docker-compose.yaml"
    dest: /root/gitlab-runner/

- name: Start Docker Compose stack
  command: docker compose up -d
  args:
    chdir: /root/gitlab-runner
