# - name: Create external network web_net
#   docker_network:
#     name: web_net
#     driver: bridge

- name: Create external network web_net
  shell: "docker network create web_net -o com.docker.network.bridge.name=web_net"

# - name: Create external network app_net
#   docker_network:
#     name: app_net
#     driver: bridge

- name: Create external network app_net
  shell: "docker network create app_net -o com.docker.network.bridge.name=app_net"

- name: Create Docker Registry
  docker_container:
    name: registry
    image: registry:2
    state: started
    restart_policy: unless-stopped
    volumes:
      - /etc/docker/registry:/var/lib/registry
    published_ports:
      - "5000:5000"
    networks:
      - name: web_net
      - name: app_net
