image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_OPTS: "--insecure-registry=127.0.0.1:5000"
  IMAGE_REPO: "127.0.0.1:5000"
  IMAGE_NAME: "go-web-app"

before_script:
  - apk update && apk add jq || { echo 'jq installation failed'; exit 1; }
  - export VERSION=$(jq -r .version appinfo.json) || { echo 'Failed to get version'; exit 1; }

.build:
  stage: build
  script:
    - docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG

build_dev:
  extends: .build
  variables:
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  only:
    - merge_requests
    - dev

deploy_dev:
  stage: deploy
  only:
    - merge_requests
    - dev
  variables:
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    PORT: "8081"
  script:
    - echo "Deploying image with Docker Compose"
    - sed -i 's|IMAGE_REPO=.*|IMAGE_REPO=$IMAGE_REPO|' .env
    - sed -i 's|IMAGE_NAME=.*|IMAGE_NAME=$IMAGE_NAME|' .env
    - sed -i 's|IMAGE_TAG=.*|IMAGE_TAG=$IMAGE_TAG|' .env
    - sed -i 's|PORT=.*|PORT=$PORT|' .env
    - docker compose up -d
