stages:
  - build
  - deploy

variables:
  DOCKER_OPTS: "--insecure-registry=registry:5000"
  IMAGE_REPO: "registry:5000"
  IMAGE_NAME: "go-web-app"

before_script:
  - apk update
  - apk add jq || { echo 'jq installation failed'; exit 1; }
  - export VERSION=$(jq -r .version appinfo.json) || { echo 'Failed to get version'; exit 1; }

.build:
  stage: build
  script:
    - docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG

build_dev:
  extends: .build
  variables:
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  only:
    - dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev"
      if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

deploy_dev:
  stage: deploy
  only:
    - dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev"
      if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  variables:
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
    PORT: "8081"
  script:
    - echo "Deploying image with Docker Compose"
    - sed -i 's|IMAGE_REPO=.*|IMAGE_REPO=$IMAGE_REPO|' .env
    - sed -i 's|IMAGE_NAME=.*|IMAGE_NAME=$IMAGE_NAME|' .env
    - sed -i 's|IMAGE_TAG=.*|IMAGE_TAG=$IMAGE_TAG|' .env
    - sed -i 's|PORT=.*|PORT=$PORT|' .env
    - docker compose up -d
