---
- hosts: server1
  become: True
  roles:
    - docker
    - kind-cluster
    # - SSL
    - nginx
    - node-exporter
    - prometheus-grafana
    - docker-image-registry
    - gitlab-runner
    - iptables-config
