stages:
  - build
  - deploy

variables:
  REGISTRY: "localhost:5000"
  IMAGE_NAME: "go-web-app"

before_script:
  - apt-get update && apt-get install -y jq
  - export VERSION=$(jq -r .version appinfo.json)

build:
  stage: build
  only:
    - main
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$VERSION .
    - docker push $REGISTRY/$IMAGE_NAME:$VERSION

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying image with blue-green strategy"
    - sed -i "s/\$TAG/$VERSION/g" docker-compose-blue.yml
    - docker-compose -f docker-compose-blue.yml up -d
    - sleep 5 # Wait for the new containers to start
    - docker-compose -f docker-compose-green.yml up -d
    - sleep 5 # Wait for the new containers to start
    - docker exec -it nginx-container nginx -s reload
