version: "3.5"

services:
  dind:
    image: docker:24.0.5-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    volumes:
      - /root/gitlab-runner/daemon.json:/etc/docker/daemon.json
      - ./data/dind/docker:/var/lib/docker
    networks:
      - web_net
      - app_net
    

  runner:
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    volumes:
      - ./config:/etc/gitlab-runner:z
      - ./data/runner/cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375
    networks:
      - web_net
      - app_net

  register-runner:
    restart: 'no'
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    depends_on:
      - dind
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=${RUNNER_NAME}
      - --executor=docker
      - --docker-privileged
      - --docker-network-mode=web_net
      - --docker-image=docker:24.0.5-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - ./config:/etc/gitlab-runner:z
      - ./data/dind/docker:/var/lib/docker
    networks:
      - web_net
      - app_net

networks:
  app_net:
    external: true
    name: app_net
  web_net:
    external: true
    name: web_net